version: '2'
services:
  consul:
    image: qnib/alpn-consul
    hostname: consul
    container_name: consul
    networks:
     - network
    environment:
     - DC_NAME=es
     - RUN_SERVER=true
     - BOOTSTRAP_CONSUL=true
     - DNS_RECURSOR=8.8.8.8
    ports:
    - "8500:8500"

  zookeeper:
    image: qnib/zookeeper
    hostname: zookeeper
    container_name: zookeeper
    extends:
      file: base.yml
      service: sojoner
    ports:
    - "2181:2181"

  kafka-broker:
    image: qnib/kafka:0.10.0.1
    hostname: kafka-broker
    container_name: kafka-broker
    extends:
      file: base.yml
      service: sojoner
    volumes:
     - /tmp/kafka-logs     
    ports:
     - "9092:9092"
  # Look at kafka for basic checking
  kafka-manager:
    image: qnib/kafka-manager
    hostname: kafka-manager
    container_name: kafka-manager
    extends:
      file: base.yml
      service: sojoner
    environment:
    - APPLICATION_SECRET=letmein
    ports:
    - "9000:9000"
  # Our Data sink
  elasticsearch:
    image: elasticsearch:1.7
    hostname: elasticsearch
    container_name: elasticsearch
    command: "elasticsearch -Des.cluster.name=clj-kstream"
    extends:
      file: base.yml
      service: sojoner
    ports:
    - "9200:9200"
    - "9300:9300"
  
  kibana: 
    image: kibana:4.1
    hostname: kibana
    container_name: kibana
    environment:
    - ELASTICSEARCH_URL=http://elasticsearch:9200
    extends:
      file: base.yml
      service: sojoner
    ports:
    - "5601:5601"

  # Our small tools
  clj-kstream-cutter:
    image: sojoner/clj-kstream-cutter:0.2.0
    hostname: clj-kstream-cutter
    container_name: clj-kstream-cutter
    extends:
      file: base.yml
      service: sojoner
    command: "--broker kafka-broker:9092 --zookeeper zookeeper:2181 --input-topic logs-replay --output-topic mapped-test-json --selector msg --name stream-cut-json-field"  

  clj-kstream-hh:
    image: sojoner/clj-kstream-hh:0.1.0
    hostname: clj-kstream-hh
    container_name: clj-kstream-hh
    extends:
      file: base.yml
      service: sojoner
    command: "--broker kafka-broker:9092 --zookeeper zookeeper:2181 --input-topic mapped-test-json --output-topic heavy-hitters --name stream-hh"  

  clj-kstream-string-long-window-aggregate:
    image: sojoner/clj-kstream-string-long-window-aggregate:0.2.2
    hostname: clj-kstream-string-long-window-aggregate
    container_name: clj-kstream-string-long-window-aggregate
    extends:
      file: base.yml
      service: sojoner
    command: "--broker kafka-broker:9092 --zookeeper zookeeper:2181 --input-topic heavy-hitters --window-size 10 --output-topic agg-result --name stream-agg"

  clj-kstream-elasticsearch-sink:
    image: sojoner/clj-kstream-elasticsearch-sink:0.0.1
    hostname: elasticsearch-sink
    container_name: elasticsearch-sink
    extends:
      file: base.yml
      service: sojoner
    command: "--broker kafka-broker:9092 --topic agg-result --elasticsearch http://elasticsearch:9200 --index 2017-hpc-test --index-type hpc-test"

  # For ever publishing text messages kafka producer for testing
  clj-kstream-lf-producer:
    image: sojoner/clj-kstream-lf-producer:0.1.0
    hostname: clj-kstream-lf-producer
    container_name: clj-kstream-lf-producer
    extends:
      file: base.yml
      service: sojoner
    command: "--broker kafka-broker:9092 --topic logs-replay"

# a network for our stack
networks:
  network:
    driver: bridge